# Setup
title: Winnie X.
tagline: ""
description: "Personal portfolio site. Theme inspired by Lando @ Mark Otto"
url: https://eager-turing-e6d8cb.netlify.app/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Winnie
  url: https://example.com
  email: winniex@stanford.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
